# Generated by Django 4.2.13 on 2024-06-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('website', models.CharField(max_length=250)),
                ('email_id', models.EmailField(max_length=250)),
                ('email_id_2', models.EmailField(blank=True, max_length=250)),
                ('tel_no', models.CharField(max_length=15)),
                ('address', models.TextField(max_length=250)),
                ('address2', models.TextField(blank=True, max_length=250)),
                ('city', models.CharField(max_length=25)),
                ('town', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=75)),
                ('technology', models.CharField(max_length=250)),
                ('technology_2', models.CharField(blank=True, max_length=250)),
                ('technology_3', models.CharField(blank=True, max_length=250)),
                ('contact_person', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'detail',
                'verbose_name_plural': 'details',
                'ordering': ('name',),
            },
        ),
    ]
